# Generated by Django 5.2.17 on 2026-08-31 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Identity', 'Identity'), ('English Test', 'English Test'), ('Certifications', 'Certifications'), ('Experience', 'Experience'), ('Application', 'Application'), ('Scholarship', 'Scholarship'), ('Other', 'Other')], default='Other', max_length=32)),
                ('fileUrl', models.TextField(blank=True)),
                ('expiryDate', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('opensDate', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('Researching', 'Researching'), ('Interested', 'Interested'), ('Eligibility Check', 'Eligibility Check'), ('Preparing', 'Preparing'), ('Application Started', 'Application Started'), ('Ready to Submit', 'Ready To Submit'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Interview', 'Interview'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waitlisted', 'Waitlisted'), ('Withdrawn', 'Withdrawn')], default='Researching', max_length=32)),
                ('priority', models.CharField(choices=[('Dream', 'Dream'), ('Target', 'Target'), ('Safe', 'Safe'), ('Backup', 'Backup')], default='Target', max_length=16)),
                ('deadline', models.CharField(blank=True, max_length=32)),
                ('funding', models.CharField(choices=[('Fully Funded', 'Fully Funded'), ('Partial', 'Partial'), ('Self-Funded', 'Self Funded'), ('Unknown', 'Unknown')], default='Unknown', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('programId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tracker.program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Research', 'Research'), ('Other', 'Other')], default='Public', max_length=16)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('dueDate', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=16)),
                ('category', models.CharField(choices=[('Research', 'Research'), ('Documents', 'Documents'), ('SOP', 'Sop'), ('Recommendation', 'Recommendation'), ('Application', 'Application'), ('Scholarship', 'Scholarship'), ('Visa', 'Visa'), ('Other', 'Other')], default='Research', max_length=32)),
                ('applicationId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tracker.application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('universityId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tracker.university')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='program',
            name='universityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='tracker.university'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('profileUrl', models.CharField(blank=True, max_length=500)),
                ('labName', models.CharField(blank=True, max_length=255)),
                ('labUrl', models.CharField(blank=True, max_length=500)),
                ('researchAreas', models.CharField(blank=True, max_length=500)),
                ('papers', models.JSONField(blank=True, default=list)),
                ('fitNotes', models.TextField(blank=True)),
                ('contactStatus', models.CharField(choices=[('Not Contacted', 'Not Contacted'), ('Researching', 'Researching'), ('Drafting Email', 'Drafting Email'), ('Emailed', 'Emailed'), ('Replied', 'Replied'), ('No Response', 'No Response'), ('Meeting Scheduled', 'Meeting Scheduled'), ('Not Pursuing', 'Not Pursuing')], default='Not Contacted', max_length=32)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=16)),
                ('lastContactedDate', models.CharField(blank=True, max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('programId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='tracker.program')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='tracker.university')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Admission', 'Admission'), ('Scholarship', 'Scholarship'), ('Funding', 'Funding'), ('Faculty', 'Faculty'), ('Research', 'Research'), ('Application', 'Application'), ('Visa', 'Visa'), ('Personal', 'Personal'), ('Other', 'Other')], default='Other', max_length=16)),
                ('applicationId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_notes', to='tracker.application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('programId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_notes', to='tracker.program')),
                ('universityId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_notes', to='tracker.university')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='universityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tracker.university'),
        ),
    ]
