# Generated by Django 5.2.3 on 2026-09-01 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('organizer', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('Academic', 'Academic'), ('Industry', 'Industry'), ('Workshop', 'Workshop'), ('Poster', 'Poster'), ('Keynote', 'Keynote'), ('Virtual', 'Virtual'), ('Other', 'Other')], default='Academic', max_length=32)),
                ('startDate', models.CharField(blank=True, max_length=32)),
                ('endDate', models.CharField(blank=True, max_length=32)),
                ('deadline', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('Researching', 'Researching'), ('Preparing', 'Preparing'), ('Submitting', 'Submitting'), ('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Attending', 'Attending'), ('Withdrawn', 'Withdrawn')], default='Researching', max_length=32)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'Phd'), ('Any', 'Any')], default='Master', max_length=16)),
                ('amount', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('deadline', models.CharField(blank=True, max_length=32)),
                ('startDate', models.CharField(blank=True, max_length=32)),
                ('endDate', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('Researching', 'Researching'), ('Preparing', 'Preparing'), ('Applying', 'Applying'), ('Submitted', 'Submitted'), ('Awarded', 'Awarded'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Researching', max_length=32)),
                ('eligibility', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
